#!/usr/bin/env python3

import olfactometer


# TODO TODO TODO round trip tests using data generated by write_test_files.py
# (but probably just refactor that stuff in here...)

def main():
    pass


if __name__ == '__main__':
    main()

