#!/usr/bin/env python3

import argparse

from olfactometer.upload import main


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--port', action='store', default='/dev/ttyACM0',
        help='port the Arduino is connected to.'
    )
    parser.add_argument('-d', '--dry-run', action='store_true', default=False,
        help='do not actually upload. just compile.'
    )
    parser.add_argument('-s', '--show-properties', action='store_true',
        default=False, help='shows arduino-cli compilation "build properties" '
        'and exits (without compiling or uploading)'
    )
    parser.add_argument('-v', '--verbose', action='store_true', default=False,
        help='make arduino-cli compilation verbose'
    )
    parser.add_argument('-g', '--arduino-debug-prints', action='store_true',
        default=False, help='compile Arduino code with DEBUG_PRINTS defined. '
        'Arduino will print more stuff over USB and its code size will increase'
        ' slightly.'
    )
    parser.add_argument('-c', '--clear-libraries', action='store_true',
        default=False, help='delete and re-create libraries'
    )
    args = parser.parse_args()

    main(
        port=args.port,
        dry_run=args.dry_run,
        show_properties=args.show_properties,
        verbose=args.verbose,
        arduino_debug_prints=args.arduino_debug_prints,
        clear_libraries=args.clear_libraries
    )

